services:
  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    ports:
      - 3001:3001

  app:
    build:
      context: ./app

    ports:
      - 3000:3000
    depends_on:
      - api